### PR TITLE
Add new components (Bibtex, RandomOrder), refresh project pages for VLDB

### PR DESCRIPTION
**Pull request by geoffxy**
In addition to what is mentioned in the commit message, I needed to modify `seo.js` to force jQuery to load before Bootstrap. Please take a look! (cc @peterbaile)

### CODE REVIEW

**Comment by peterbaile** [comment]
hi @geoffxy , this looks great 👍 

a few comments:
1. could you change `bibtex.js` into functional components (just like what I did for the other components), should be fairly straightforward. functional components are faster performance-wise
2. could you move `random_order.js` to `src/utils`

thanks!

**Comment by geoffxy** [comment]
Thanks @peterbaile - I've made the two changes - please take a look! Should I be running prettier on the code or any linters?

**Comment by peterbaile** [comment]
great! i think we don't need linters for now

**Review by peterbaile — APPROVED** [review]
good to go

**Pull request merged**
